### ISSUE TITLE
ローカルとリモートの環境で、ヤンクした情報をシステムクリップボードに移すように調整

### ISSUE THREAD

**Issue by raptowl** [raptowl/dotfiles#2]
## Objective

ローカルとリモートの環境で、ヤンクした情報をシステムクリップボードに移すように調整する。

- tmux の設定
- vim の設定
- ポートフォワードと nc コマンドを連携させた設定
- nc コマンドとシステムクリップボードにコピーさせるコマンドを連携させた設定

## Prerequisites

なし

## Achievement-Requirements

- ローカルとリモートで、同じインターフェースで、シームレスにクリップボード連携ができる

## Tasks

- [ ]
- [ ]

**Comment by raptowl** [comment]
メモ

- tmuxのバッファーとシステムのクリップボードを共通化させるフィルタコマンドを作る
    - リモートではフォワードさせたポートに`nc`で流し込むようにする
    - ローカルでは、システムにインストールされたコマンドを使用するように

**Comment by raptowl** [comment]
## ヤンクする場面

- ローカルの vim でヤンク:
  - ローカルのクリップボードにコピー
- ローカルの tmux でヤンク:
  - ローカルのクリップボードにコピー
- リモートの vim でヤンク:
  - ローカルのクリップボードにコピー
- リモートの tmux でヤンク:
  - ローカルのクリップボードにコピー

## ペーストする場面

- ローカルの vim でペースト:
  - ローカルのクリップボードから(alacritty で Ctrl+Shift+V)
  - ローカルの vim から(p)
- ローカルの tmux でペースト:
  - ローカルのクリップボードから(alacritty で Ctrl+Shift+V)
  - ローカルの tmux から(Ctrl+t -> Ctrl+p)
- リモートの vim でペースト:
  - ローカルのクリップボードから(alacritty で Ctrl+Shift+V)
  - リモートの vim から(p)
- リモートの tmux でペースト:
  - ローカルのクリップボードから(alacritty で Ctrl+Shift+V)
  - リモートの tmux から(Ctrl+t -> Ctrl+p)

**Comment by raptowl** [comment]
フィルタコマンド ~~`cbc`~~`cbd` (ClipBoarD) を `bin/` 配下に作成した。
ブランチ: `feature/improve_yank`

- [x] インストールされているシステムクリップボード連携コマンドを判別して、標準入力からクリップボードにコピーする処理を作成
- [x] 標準出力へのアウトプット、クリップボードのクリアを行う動作オプションを設ける
- [x] リモートログイン環境かローカルホストかを判別して、リモートの場合はポートフォワードさせる処理を追加
  - 別のオプションなしのフィルタコマンドを用意
  - 名称: rcbp - Remote ClipBoard Pipieline 
- [ ] vim のヤンク及び tmux のヤンクと連携させて、クリップボードにデータを取れるようにする
  - [ ] vim
  - [ ] tmux
- [ ] ポートフォワードされてきたデータを自動でキャッチするデーモンを動かす設定
  - [ ] Linux の場合は systemd?
  - [ ] macOS の場合は clipper?(要調査)

**Comment by raptowl** [comment]
[コメント](https://github.com/raptowl/dotfiles/issues/2#issuecomment-970402202)に記述した内容で、一部使用変更した箇所を、以下に記す。

- クリップボードへの入力を扱うコマンドは、1つに統一: `cbdi` - ClipBoarD Input
  - 実行時に、環境変数の値を読み取って、ローカルのクリップボードマネージャへ渡すか、ポートフォワードさせるか、で処理を分岐させる

残りTODO追加
- PC の systemd に、クリップボードへ渡すための unit を作成する(ユーザースペース)
  - 参考情報
    - https://enakai00.hatenablog.com/entry/20130914/1379146157
    - https://qiita.com/ma2shita/items/f366320cc504c04b6b6a
    - https://wiki.archlinux.jp/index.php/Systemd/%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC
